server:
  port: 8080
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.springdemo.Entities
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_employee
    username: root
    password:
  redis:
    host: localhost
    port: 6379
    database: 15
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html